[Interface]
PrivateKey = cM6B0pNX0wZ6mB66te/MnBRWMV5+SBVZwdWZfoHnPGM=
Address = 172.16.0.2/32, 2606:4700:110:875b:e0fc:431f:6ee0:daca/128
DNS = 1.1.1.1
MTU = 1280
[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = engage.cloudflareclient.com:2408
Reserved = [158, 104, 53]