[Interface]
PrivateKey = kDF46njz2oanohYlxX1GUf9l9fnHfBQ9taYz8ZVXh1U=
Address = 172.16.0.2/32, 2606:4700:110:88c0:477b:6b78:49a7:a9dd/128
DNS = 1.1.1.1
MTU = 1280
[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = engage.cloudflareclient.com:2408
Reserved = [119, 239, 55]